fix

diff --git a/.github/workflows/generate-config-out.yml b/.github/workflows/generate-config-out.yml
--- a/.github/workflows/generate-config-out.yml
+++ b/.github/workflows/generate-config-out.yml
@@ -65,4 +65,9 @@ jobs:
           github_token: ${{steps.generate_token.outputs.token}}
           branch: ${{inputs.branch}}
           file: ${{inputs.file}}
-          args: "--no-comment"
+          args: "--no-comment --no-label"
+
+      - name: List generated files
+        run: |
+          echo "Listing generated_*.tf"
+          ls -la generated_*.tf || echo "Not found"
